# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ulee <ulee@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/12/21 20:05:22 by ulee              #+#    #+#              #
#    Updated: 2021/12/22 15:34:03 by ulee             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	clang++ -std=c++98 -Wall -Wextra -Werror Phonebook.cpp Contact.cpp main.cpp -o Phonebook; ./Phonebook
clean:
	rn megaphone
